Update postmerge.yml

diff --git a/.github/workflows/postmerge.yml b/.github/workflows/postmerge.yml
--- a/.github/workflows/postmerge.yml
+++ b/.github/workflows/postmerge.yml
@@ -8,6 +8,8 @@ on:
 jobs:
   run-tests:
     runs-on: ubuntu-latest
+    permissions:
+      contents: write  # Allows the action to push to the repository
 
     steps:
       - name: Checkout code
@@ -15,15 +17,16 @@ jobs:
 
       - name: Run Check
         run: |
-          echo "Running test"
-          exit 1   
+          echo "Running ESLint"
+          exit 1  # Simulating failure for testing purposes
 
       - name: Revert last commit
-        if: failure() 
+        if: failure()  # This step runs if the previous steps fail
         env:
-          PAT_TOKEN: ${{secrets.PAT_TOKEN }}
+          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
         run: |
-                git config --local user.email "ashfaqonly1@gmail.com"
-                git config --local user.name "Ashfaq"
-                git revert HEAD --no-edit
-                git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ashfaq11/workflowtest.git main
+          git config --local user.email "ashfaqonly1@gmail.com"
+          git config --local user.name "Ashfaq"
+          git revert HEAD --no-edit
+          git remote set-url origin https://$PAT_TOKEN@github.com/ashfaq11/workflowtest.git
+          git push --force origin main
